name: BarleyTeaAPI-Examples
version: 1.0.0
api-version: 1.20
author: new1271 (RiceTeaInMC)
main: org.ricetea.barleyteaapi.example.BarleyTeaAPIExample
description: an example plugin for BarleyTeaAPI
depend:
  - "BarleyTeaAPI"

